In [11]:
import torch

x = torch.arange(12)

x.shape

x.numel()

x.reshape(3,4)


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [16]:
import torch

torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [17]:
import torch

torch.tensor([1,2,3])

tensor([1, 2, 3])

In [22]:
import torch

x = torch.tensor([1.0,2,4,8])
y = torch.tensor([2,2,2,2])
x + y,x * y,x / y,x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [24]:
import torch

X = torch.arange(12,dtype=torch.float32).reshape(3,4)
Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=1)

X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [2]:
import torch

a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a,b

a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])